### ISSUE TITLE
couldn't find UnityEngine.dll

### ISSUE THREAD

**Issue by jaden133** [AtiLion/Blackwake-CTrinity#2]
couldn't find UnityEngine.dll when building solution

**Comment by AtiLion** [comment]
Did you follow the instructions correctly?

**Comment by AtiLion** [comment]
The dlls save into the main directory then /bin/Debug

**Comment by jaden133** [comment]
Then when i click the injector.exe MonoLoader.dll not found error

**Comment by AtiLion** [comment]
Make sure all dlls are in the same directory
